apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: test1
  janus-idp.io/tekton: test1
  backstage.io/kubernetes-id: test1
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: test1
resources:
- deployment.yaml
- route.yaml
- service.yaml
