apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test1 
  name: test1
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: test1 
